# Data Preparation

In [4]:
import numpy as np
import pandas as pd

## 1_listing

In [3]:
listing = pd.read_json('./files/listings_final_expanded.json')

In [4]:
listing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  object
 1   City           21200 non-null  object
 2   Property_Type  21200 non-null  object
 3   Price          21200 non-null  float64
 4   Sqft           21200 non-null  float64
 5   Date_Listed    21200 non-null  object
 6   Agent_ID       21200 non-null  object
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: float64(4), object(5)
memory usage: 1.5+ MB

In [5]:
listing.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [6]:
listing[['Price', 'Sqft']] = listing[['Price', 'Sqft']].round().astype('int64')

In [7]:
listing['Date_Listed'] = pd.to_datetime(listing['Date_Listed'])

In [8]:
listing['Date_Listed'].dtypes

dtype('<M8[ns]')

In [9]:
listing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  object
 1   City           21200 non-null  object
 2   Property_Type  21200 non-null  object
 3   Price          21200 non-null  int64
 4   Sqft           21200 non-null  int64
 5   Date_Listed    21200 non-null  datetime64[ns]
 6   Agent_ID       21200 non-null  object
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 1.5+ MB

## 2_property_attributes

In [10]:
property_attributes = pd.read_json('./files/property_attributes_final_expanded.json')

In [11]:
property_attributes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  object
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  bool
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  object
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  bool
 12  power_backup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

In [12]:
property_attributes.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [13]:
property_attributes['is_rented'].replace({True: 1, False: 0}, inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14116\3635538518.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  property_attributes['is_rented'].replace({True: 1, False: 0}, inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14116\3635538518.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  property_attributes['is_rented'].replace({True: 1, False: 0}, inplace=True)

In [14]:
property_attributes['parking_available']=property_attributes['parking_available'].astype('int')

In [15]:
property_attributes['power_backup']=property_attributes['power_backup'].replace({True:1, False:0})

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14116\1950098862.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  property_attributes['power_backup']=property_attributes['power_backup'].replace({True:1, False:0})

In [16]:
property_attributes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  object
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  int64
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  object
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  int64
 12  power_backup       21200 non-null  int64
dtypes: float64(1), int64(10), object(2)
memory usage: 2.1+ MB

## 3_agents

In [17]:
agents = pd.read_json('./files/agents_cleaned.json')

In [18]:
agents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Agent_ID          50 non-null     object
 1   Name              50 non-null     object
 2   Phone             50 non-null     object
 3   Email             50 non-null     object
 4   commission_rate   50 non-null     float64
 5   deals_closed      50 non-null     int64
 6   rating            50 non-null     float64
 7   experience_years  50 non-null     int64
 8   avg_closing_days  50 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.6+ KB

In [19]:
agents.head()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

## 4_sales

In [20]:
sales = pd.read_csv('./files/sales_cleaned.csv')

In [21]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_ID      720 non-null    object
 1   Sale_Price      720 non-null    float64
 2   Date_Sold       720 non-null    object
 3   Days_on_Market  720 non-null    float64
dtypes: float64(2), object(2)
memory usage: 22.6+ KB

In [22]:
sales.head()

  Listing_ID    Sale_Price   Date_Sold  Days_on_Market
0     L01179  9.255800e+05  2023-07-07       65.005560
1     L00866  1.054160e+05  2023-06-14       38.004620
2     L00102  1.825184e+06  2023-09-09       22.992622
3     L00440  1.932085e+06  2023-10-29       72.012274
4     L00059  7.765860e+05  2023-05-01      116.000152

In [23]:
sales['Date_Sold'] = pd.to_datetime(sales['Date_Sold'])

In [24]:
sales['Sale_Price'] = sales['Sale_Price'].round().astype('int')

In [25]:
sales['Days_on_Market'] = sales['Days_on_Market'].astype('int')

In [26]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_ID      720 non-null    object
 1   Sale_Price      720 non-null    int64
 2   Date_Sold       720 non-null    datetime64[ns]
 3   Days_on_Market  720 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 22.6+ KB

## 5_buyers

In [27]:
buyers = pd.read_json('./files/buyers_cleaned.json')

In [28]:
buyers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   buyer_id       20000 non-null  int64
 1   sale_id        20000 non-null  object
 2   buyer_type     20000 non-null  object
 3   payment_mode   20000 non-null  object
 4   loan_taken     20000 non-null  bool
 5   loan_provider  10034 non-null  object
 6   loan_amount    20000 non-null  int64
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB

In [29]:
buyers

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221
...,...,...,...,...,...,...,...
19995,19996,L00891,Investor,UPI,False,None,0
19996,19997,L00834,End User,UPI,False,None,0
19997,19998,L01188,Investor,UPI,False,None,0
19998,19999,L00905,Investor,Cheque,True,ICICI,3701968
19999,20000,L00526,Investor,Cash,True,SBI,3805678

In [30]:
buyers['loan_taken'] = buyers['loan_taken'].astype('int')

In [31]:
buyers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   buyer_id       20000 non-null  int64
 1   sale_id        20000 non-null  object
 2   buyer_type     20000 non-null  object
 3   payment_mode   20000 non-null  object
 4   loan_taken     20000 non-null  int64
 5   loan_provider  10034 non-null  object
 6   loan_amount    20000 non-null  int64
dtypes: int64(3), object(4)
memory usage: 1.1+ MB

# Database Creation (mySQL)

In [46]:
import mysql.connector

mydb = mysql.connector.connect(
    host='localhost',
    user='root',
    password='Iphone6+'
)

mycursor = mydb.cursor()

## create database project_1

In [48]:
mycursor.execute('CREATE DATABASE IF NOT EXISTS project_1')

mycursor.execute('USE project_1')

mydb.commit()

## Table creation and inserting values

### 1_listing

In [220]:
listing.columns

Index(['Listing_ID', 'City', 'Property_Type', 'Price', 'Sqft', 'Date_Listed',
       'Agent_ID', 'Latitude', 'Longitude'],
      dtype='object')

In [221]:
mycursor.execute("""
    CREATE TABLE IF NOT EXISTS listing(
        Listing_ID VARCHAR(50) PRIMARY KEY,
        City VARCHAR(50),
        Property_Type VARCHAR(50),
        Price INT,
        Sqft INT,
        Date_Listed DATE,
        Agent_ID VARCHAR(50),
        Latitude FLOAT,
        Longitude FLOAT
    )
""")

mydb.commit()

insert data

In [222]:
listing_values = listing.values.tolist()

query = """
            INSERT INTO listing (Listing_ID, City, Property_Type, Price, Sqft, Date_Listed, Agent_ID, Latitude, Longitude) 
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """

mycursor.executemany(query, listing_values)
mydb.commit()

### 2_property_attributes

In [157]:
property_attributes.columns

Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='object')

In [230]:
mycursor.execute("""
    CREATE TABLE IF NOT EXISTS property_attributes (
        Attribute_ID INT UNIQUE AUTO_INCREMENT,
        Listing_ID VARCHAR(50) NOT NULL,
        FOREIGN KEY (Listing_ID) REFERENCES listing(Listing_ID) ON DELETE CASCADE ON UPDATE CASCADE,
        Bedrooms INT CHECK (Bedrooms <= 8),
        Bathrooms INT CHECK (Bathrooms <= 8),
        Floor_Number INT,
        Total_Floors INT,
        Year_Built YEAR,
        Is_Rented BOOLEAN,
        Tenant_Count INT,
        Furnishing_Status VARCHAR(50) CHECK (Furnishing_Status IN ('Furnished', 'Unfurnished', 'Semi-Furnished')),
        Metro_Distance_km FLOAT,
        Parking_Available BOOLEAN,
        Power_Backup BOOLEAN
        )

""")

mydb.commit()

Insert data

In [231]:
property_attributes_values = property_attributes.values.tolist()

query = """
            INSERT INTO property_attributes (Attribute_ID, Listing_ID, Bedrooms, Bathrooms, Floor_Number, Total_Floors, Year_Built, Is_Rented , Tenant_Count, Furnishing_Status, Metro_Distance_km, Parking_Available, Power_Backup)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """

mycursor.executemany(query, property_attributes_values)

mydb.commit()

### 3_agents

In [232]:
agents.columns

Index(['Agent_ID', 'Name', 'Phone', 'Email', 'commission_rate', 'deals_closed',
       'rating', 'experience_years', 'avg_closing_days'],
      dtype='object')

In [233]:
mycursor.execute("""
    CREATE TABLE IF NOT EXISTS agents (
        Agent_ID VARCHAR(50) UNIQUE,
        Name VARCHAR(50),
        Phone VARCHAR(20),
        Email VARCHAR(50),
        Commission_Rate INT,
        Deals_Closed INT,
        Rating FLOAT CHECK (Rating > 0 AND Rating <= 5),
        Experience_Years INT,
        Avg_Closing_Days INT
        )
""")

mydb.commit()

insert data

In [234]:
agents_values = agents.values.tolist()

query = """
            INSERT INTO agents (Agent_ID, Name, Phone, Email, Commission_Rate, Deals_Closed, Rating, Experience_Years, Avg_Closing_Days)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """

mycursor.executemany(query, agents_values)

mydb.commit()

### 4_sales

In [191]:
sales.columns

Index(['Listing_ID', 'Sale_Price', 'Date_Sold', 'Days_on_Market'], dtype='object')

In [255]:
mycursor.execute("""
    CREATE TABLE IF NOT EXISTS sales (
        Listing_ID VARCHAR(50) NOT NULL, 
        FOREIGN KEY (Listing_ID) REFERENCES listing(Listing_ID) ON DELETE CASCADE ON UPDATE CASCADE,
        Sale_Price INT,
        Date_Sold DATE,
        Days_on_Market INT
        )                 
""")

mydb.commit()

In [254]:
mycursor.execute('DROP TABLE sales')
mydb.commit()

insert data

In [266]:
sales_value = sales.values.tolist()

query = """
            INSERT INTO sales (Listing_ID, Sale_Price, Date_Sold, Days_on_Market)
            VALUES (%s, %s, %s, %s)
        """

mycursor.executemany(query, sales_value)
mydb.commit()

### 5_buyers

In [268]:
buyers.columns

Index(['buyer_id', 'sale_id', 'buyer_type', 'payment_mode', 'loan_taken',
       'loan_provider', 'loan_amount'],
      dtype='object')

In [279]:
mycursor.execute("""
    CREATE TABLE IF NOT EXISTS buyers (
        Buyer_ID INT UNIQUE AUTO_INCREMENT,
        Sale_ID VARCHAR(50),
        Buyer_Type VARCHAR(50) CHECK (Buyer_Type in ('End User', 'Investor')),
        Payment_Mode VARCHAR(50),
        Loan_Taken BOOLEAN,
        Loan_Provider VARCHAR(50),
        Loan_Amount INT
        )                 
""")

mydb.commit()

insert data

In [280]:
buyers_value = buyers.values.tolist()

query = """
            INSERT INTO buyers (Buyer_ID, Sale_ID, Buyer_Type, Payment_Mode, Loan_Taken, Loan_Provider, Loan_Amount)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """

mycursor.executemany(query, buyers_value)

mydb.commit()

# Data Analysis with SQL Queries

## Property & Pricing Analysis

### 1.What is the average listing price by city?

In [7]:
query = """
            SELECT City, AVG(Price) AS Avg_Price 
            FROM listing
            GROUP BY City
            ORDER BY Avg_Price DESC;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for city, avg_price in rows:
#     print(city, avg_price)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

          City     Avg_Price
0     New York  2493319.7416
1      Phoenix  2459961.7642
2  Los Angeles  2442418.3191
3      Houston  2436811.0022
4      Chicago  2430677.9019

In [ ]:
# pandas method

listing.groupby('City')['Price'].mean()

### 2.What is the average price per square foot by property type?

In [10]:
query = """
            SELECT Property_Type, ROUND(AVG(Price / Sqft)) AS Avg_Price_per_Sqft
            FROM listing
            GROUP BY Property_Type
            ORDER BY Avg_Price_per_Sqft
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in values:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

  Property_Type Avg_Price_per_Sqft
0         Condo                755
1     Townhouse                790
2     Apartment                792
3         House                796

In [318]:
# pandas method

# listing['Price_Per_Sqft'] = listing['Price'] / listing['Sqft'] 
# listing.groupby(['Property_Type])[Price_Per_Sqft].mean()

listing.groupby(['Property_Type']).apply(lambda x: (x['Price']/x['Sqft']).mean()).sort_values()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10012\1631495538.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  listing.groupby(['Property_Type']).apply(lambda x: (x['Price']/x['Sqft']).mean()).sort_values()

Property_Type
Condo        754.681347
Townhouse    789.746749
Apartment    792.196465
House        796.042454
dtype: float64

### 3.How does furnishing status impact property prices?

In [12]:
query = """
            SELECT pa.Furnishing_Status, AVG(l.Price) AS Avg_Price
            FROM listing l
            INNER JOIN property_attributes pa
                ON l.Listing_ID = pa.Listing_ID
            GROUP BY pa.Furnishing_Status
            ORDER BY Avg_Price DESC;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Furnishing_Status     Avg_Price
0         Furnished  2463539.0641
1    Semi-Furnished  2461192.6568
2       Unfurnished  2433975.1000

### 4.Do properties closer to metro stations command higher prices?

In [342]:
property_attributes['metro_distance_km'].min()

np.float64(0.1)

In [ ]:
property_attributes['metro_distance_km'].max()

np.float64(15.0)

In [13]:
query = """
            SELECT 
                CASE
                    WHEN pa.Metro_Distance_Km <= 1 THEN '<= 1 KM'
                    WHEN pa.Metro_Distance_Km > 1 AND pa.Metro_Distance_Km <=3 THEN '1-3 KM'
                    WHEN pa.Metro_Distance_Km > 3 AND pa.Metro_Distance_Km <=5 THEN '3-5 KM'
                    WHEN pa.Metro_Distance_Km > 5 AND pa.Metro_Distance_Km <=10 THEN '5-10 KM'
                    WHEN pa.Metro_Distance_Km > 10 AND pa.Metro_Distance_Km <=15 THEN '10-15 KM'
                END AS Distance,
                ROUND(AVG(l.Price)) AS Avg_Price
            FROM Listing l
            INNER JOIN Property_Attributes pa
                ON l.Listing_ID = pa.Listing_ID
            GROUP BY Distance
            ORDER BY Avg_Price;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

   Distance Avg_Price
0   <= 1 KM   2386849
1    3-5 KM   2392399
2    1-3 KM   2399214
3   5-10 KM   2442977
4  10-15 KM   2527729

### 5.Are rented properties priced differently from non-rented ones?

In [16]:
query = """
            SELECT 
                CASE
                    WHEN pa.Is_Rented = 0 THEN 'Not Rented'
                    WHEN pa.Is_Rented = 1 THEN 'Rented'
                END AS Rented_Status,
                ROUND(AVG(l.Price), 2) AS Avg_Price
            FROM Listing l
            INNER JOIN Property_Attributes pa
                ON l.Listing_ID = pa.Listing_ID
            GROUP BY Rented_Status
            ORDER BY Avg_Price;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

  Rented_Status   Avg_Price
0    Not Rented  2448250.30
1        Rented  2457184.91

### 6.How do bedrooms and bathrooms affect pricing?

In [368]:
property_attributes['bedrooms'].unique()

array([5, 2, 3, 1, 4])

In [366]:
property_attributes['bathrooms'].unique()

array([3, 2, 1, 4])

In [ ]:
query = """
            SELECT pa.Bedrooms, pa.Bathrooms, ROUND(AVG(l.Price)) AS Avg_Price
            FROM Listing l
            INNER JOIN Property_Attributes pa
                ON  l.Listing_ID = pa.Listing_ID
            GROUP BY pa.Bedrooms, pa.Bathrooms
            ORDER BY pa.Bedrooms;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j, k in r:
#     print(i, j, k)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

    Bedrooms  Bathrooms Avg_Price
0          1          1   2434001
1          1          2   2509475
2          1          3   2459033
3          1          4   2455533
4          2          1   2455735
5          2          2   2378688
6          2          3   2482619
7          2          4   2555766
8          3          1   2426008
9          3          2   2409123
10         3          3   2455024
11         3          4   2478881
12         4          1   2434956
13         4          2   2450750
14         4          3   2393515
15         4          4   2471536
16         5          1   2384940
17         5          2   2478068
18         5          3   2424067
19         5          4   2527192

### 7.Do properties with parking and power backup sell at higher prices?

In [25]:
query = """
            SELECT 
                CASE 
                    WHEN pa.Parking_Available = 0 THEN 'Not Available'
                    ELSE 'Available' 
                END AS Parking,
                CASE
                    WHEN pa.Power_Backup = 0 THEN 'Not Available'
                    ELSE 'Available'
                END AS Power_Backup,
                ROUND(AVG(l.Price)) AS Avg_Price
            FROM Listing l
            INNER JOIN Property_Attributes pa
                ON l.Listing_ID = pa.Listing_ID
            GROUP BY Parking, Power_Backup
            ORDER BY Avg_Price;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j, k, in r:
#     print(i, j, k)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns= c)

         Parking   Power_Backup Avg_Price
0  Not Available  Not Available   2436678
1  Not Available      Available   2446293
2      Available  Not Available   2462364
3      Available      Available   2465652

### 8.How does year built influence listing price?

In [44]:
property_attributes['year_built'].unique()

array([2001, 2020, 2007, 2003, 2008, 2000, 2012, 2023, 1996, 2021, 2010,
       2002, 2022, 1999, 2015, 2014, 1998, 1997, 2017, 2013, 2004, 1995,
       2009, 2006, 2019, 2018, 2016, 2005, 2011, 1990, 1991, 1994, 1992,
       1993])

In [26]:
query = """
            SELECT pa.Year_Built, ROUND(AVG(l.Price),2) AS Avg_Price
            FROM Listing l
            INNER JOIN Property_Attributes pa
                ON l.Listing_ID = pa.Listing_ID
            GROUP BY pa.Year_Built
            ORDER BY pa.Year_Built
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

    Year_Built   Avg_Price
0         1990  2533791.60
1         1991  2573916.57
2         1992  2594651.57
3         1993  2611748.27
4         1994  2571504.91
5         1995  2434727.72
6         1996  2391385.74
7         1997  2493105.19
8         1998  2398158.87
9         1999  2498402.49
10        2000  2436148.37
11        2001  2438764.29
12        2002  2433615.48
13        2003  2395754.95
14        2004  2410642.68
15        2005  2518303.23
16        2006  2464741.45
17        2007  2379428.80
18        2008  2471225.26
19        2009  2401619.12
20        2010  2401119.99
21        2011  2440249.45
22        2012  2302495.50
23        2013  2348081.45
24        2014  2358476.99
25        2015  2457272.06
26        2016  2428168.80
27        2017  2393633.48
28        2018  2385864.54
29        2019  2561310.34
30        2020  2465414.49
31        2021  2545272.17
32        2022  2397386.63
33        2023  2500120.42

### 9.Which cities have the highest median property prices?

In [31]:
# step 1

query = """
            SELECT 
                City,
                Price,
                ROW_NUMBER() OVER(PARTITION BY City ORDER BY Price) AS rn,
                COUNT(*) OVER(PARTITION BY City) AS cnt
            FROM listing
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c).head()

      City   Price  rn   cnt
0  Chicago  100082   1  4293
1  Chicago  101958   2  4293
2  Chicago  103179   3  4293
3  Chicago  106673   4  4293
4  Chicago  106825   5  4293

In [ ]:
# step 2

query = """
            with ordered_price AS (
                SELECT 
                    City,
                    Price,
                    ROW_NUMBER() OVER(PARTITION BY City ORDER BY Price) AS rn,
                    COUNT(*) OVER(PARTITION BY City) AS cnt
                FROM listing
            )
            SELECT
                City,
                ROUND(AVG(Price)) as median
            FROM ordered_price
            WHERE rn IN (FLOOR((cnt+1)/2), FLOOR((cnt+2) /2))
            GROUP BY City;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

          City   median
0      Chicago  2351084
1      Houston  2347582
2  Los Angeles  2380930
3     New York  2446519
4      Phoenix  2397598

### 10.How are properties distributed across price buckets?

In [57]:
listing['Price'].min()

np.int64(100027)

In [55]:
listing['Price'].max()

np.int64(4999864)

In [44]:
query = """
            SELECT 
                CASE
                    WHEN Price BETWEEN 1000000 AND 2000000 THEN '100K-200K'
                    WHEN Price BETWEEN 2000001 AND 3000000 THEN '200K-300K'
                    WHEN Price BETWEEN 3000001 AND 4000000 THEN '300K-400K'
                    WHEN Price BETWEEN 4000001 AND 5000000 THEN '400K-500K'
                    ELSE '500K+'
                END AS Price_Bucket,
                COUNT(*) AS Total_Properties
            FROM Listing
            GROUP BY Price_Bucket
            ORDER BY 
                CASE Price_Bucket
                    WHEN '100K-200K' THEN 1
                    WHEN '200K-300K' THEN 2
                    WHEN '300K-400K' THEN 3
                    WHEN '400K-500K' THEN 4
                    ELSE 5
                END;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i in r:
#     print(i)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Price_Bucket  Total_Properties
0    100K-200K              4800
1    200K-300K              4025
2    300K-400K              4083
3    400K-500K              4023
4        500K+              4269

## Sales & Market Performance

### 11.What is the average days on market by city?

In [49]:
query = """
            SELECT 
                l.City,
                ROUND(AVG(s.Days_on_Market)) AS Avg_Days_on_Market
            FROM Listing l
            INNER JOIN Sales s
                ON l.Listing_ID = s.Listing_ID
            GROUP BY l.City
            ORDER BY Avg_Days_on_Market
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

          City Avg_Days_on_Market
0      Houston                 58
1      Phoenix                 59
2     New York                 60
3      Chicago                 64
4  Los Angeles                 65

### 12.Which property types sell the fastest?

In [50]:
query = """
            SELECT 
                l.Property_Type,
                ROUND(AVG(s.Days_on_Market)) AS Avg_Days_on_Market
            FROM Listing l
            INNER JOIN Sales s
                ON l.Listing_ID = s.Listing_ID
            GROUP BY l.Property_Type
            ORDER BY Avg_Days_on_Market
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

  Property_Type Avg_Days_on_Market
0         House                 58
1     Townhouse                 60
2     Apartment                 60
3         Condo                 66

### 13.What percentage of properties are sold above listing price?

In [51]:
query = """
            WITH percentage_price AS (
                SELECT 
                    l.City,
                    CASE
                        WHEN s.Sale_Price > l.Price THEN 1
                        ELSE 0
                    END AS price_above_listing
                FROM listing l
                INNER JOIN sales s
                    ON l.Listing_ID = s.Listing_ID
            )
            SELECT
                City,
                ROUND(100 * SUM(price_above_listing) / COUNT(*), 2) AS sold_above_listing_price
            FROM percentage_price
            GROUP BY City
            ORDER BY sold_above_listing_price DESC;
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j in r:
#     print(i, j)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

          City sold_above_listing_price
0      Houston                    54.20
1      Chicago                    50.64
2     New York                    48.91
3      Phoenix                    47.02
4  Los Angeles                    46.09

### 14.What is the sale-to-list price ratio by city?

In [54]:
query = """
            SELECT 
                l.City,
                ROUND(AVG(s.Sale_Price / l.Price)) AS Sale_to_List_Ratio,
                COUNT(*) AS total_sales
            FROM Listing l
            INNER JOIN Sales s
                ON l.Listing_ID = s.Listing_ID
            GROUP BY l.City
            ORDER BY Sale_to_List_Ratio
        """

mycursor.execute(query)

r = mycursor.fetchall()

# for i, j, k in r:
#     print(i, j, k)

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns=c)

          City Sale_to_List_Ratio  total_sales
0      Phoenix                  1          168
1      Houston                  1          131
2      Chicago                  1          156
3  Los Angeles                  1          128
4     New York                  1          137

### 15.Which listings took more than 90 days to sell?

In [59]:
query = """
    SELECT 
        l.Listing_ID, l.City, l.Property_Type, s.Days_on_Market
    FROM Listing l
    INNER JOIN Sales s
        ON l.Listing_ID = s.Listing_ID
    WHERE s.Days_on_Market >= 90
    ORDER BY s.Days_on_Market DESC;
    """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

    Listing_ID         City Property_Type  Days_on_Market
0       L00157      Phoenix     Townhouse             120
1       L00179      Chicago         Condo             120
2       L00259      Phoenix     Apartment             120
3       L00057      Phoenix         Condo             119
4       L00287      Houston     Townhouse             119
..         ...          ...           ...             ...
185     L00045  Los Angeles         House              90
186     L00992      Houston         House              90
187     L00452  Los Angeles         House              90
188     L00568      Chicago         House              90
189     L00812      Houston         House              90

[190 rows x 4 columns]

### 16.How does metro distance affect time on market?

In [60]:
query = """
            SELECT 
                CASE
                    WHEN pa.Metro_Distance_Km <= 1 THEN '<= 1 KM'
                    WHEN pa.Metro_Distance_Km > 1 AND pa.Metro_Distance_Km <=3 THEN '1-3 KM'
                    WHEN pa.Metro_Distance_Km > 3 AND pa.Metro_Distance_Km <=5 THEN '3-5 KM'
                    WHEN pa.Metro_Distance_Km > 5 AND pa.Metro_Distance_Km <=10 THEN '5-10 KM'
                    WHEN pa.Metro_Distance_Km > 10 AND pa.Metro_Distance_Km <=15 THEN '10-15 KM'
                END AS Distance,
                ROUND(AVG(s.Days_on_Market)) AS Avg_Day_on_Market
            FROM sales s
            INNER JOIN property_attributes pa
                ON s.Listing_ID = pa.Listing_ID
            GROUP BY Distance
            ORDER BY Distance
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Distance Avg_Day_on_Market
0  <= 1 KM                64
1   1-3 KM                64
2   3-5 KM                59
3  5-10 KM                60

### 17.What is the monthly sales trend?

In [98]:
sales.head()

  Listing_ID  Sale_Price  Date_Sold  Days_on_Market
0     L01179      925580 2023-07-07              65
1     L00866      105416 2023-06-14              38
2     L00102     1825184 2023-09-09              22
3     L00440     1932085 2023-10-29              72
4     L00059      776586 2023-05-01             116

In [67]:
query = """
            SELECT 
                DATE_FORMAT(s.Date_Sold, '%Y-%m') AS Sale_Month,
                COUNT(*) AS Sales_Count,
                ROUND(AVG(s.Sale_Price)) AS Avg_Sales
            FROM sales s
            GROUP BY Sale_Month
            ORDER BY Sale_Month;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

   Sale_Month  Sales_Count Avg_Sales
0     2023-01            7    756914
1     2023-02           17    937945
2     2023-03           20    999753
3     2023-04           36   1228007
4     2023-05           45   1141904
5     2023-06           31    956240
6     2023-07           48   1166671
7     2023-08           50   1101013
8     2023-09           46   1084102
9     2023-10           64   1096915
10    2023-11           46   1086330
11    2023-12           42   1090327
12    2024-01           44   1091116
13    2024-02           44   1128125
14    2024-03           39   1061516
15    2024-04           29   1036853
16    2024-05           45   1004163
17    2024-06           29   1017186
18    2024-07           24   1067378
19    2024-08           13    986429
20    2024-09            1    229304

### 18.Which properties are currently unsold?

In [68]:
query = """
            SELECT
                l.Property_Type,
                COUNT(*) AS unsold
            FROM listing l
            LEFT JOIN sales s
                ON l.Listing_ID = s.Listing_ID
            WHERE s.Listing_ID IS NULL
            GROUP BY l.Property_Type
            ORDER BY unsold;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Property_Type  unsold
0     Townhouse    5005
1         House    5140
2     Apartment    5159
3         Condo    5176

## Agent Performance

### 19.Which agents have closed the most sales?

In [70]:
query = """
            SELECT Agent_ID, Name, Deals_Closed 
            FROM agents
            ORDER BY Deals_Closed DESC LIMIT 1;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Agent_ID         Name  Deals_Closed
0    A0003  Agent A0003           297

### 20.Who are the top agents by total sales revenue?

In [71]:
query = """
            WITH agent_revenue AS(
                SELECT 
                    a.Agent_ID, 
                    a.Name,
                    SUM(s.Sale_Price) AS total_sales_revenue,
                    COUNT(s.Listing_ID) AS total_sales_count
                FROM agents a
                INNER JOIN listing l
                    ON a.Agent_ID = l.Agent_ID
                INNER JOIN sales s
                    ON l.Listing_ID = s.Listing_ID
                GROUP BY a.Agent_ID, a.Name
                ORDER BY total_sales_revenue DESC
            ),
            ranked_agents AS (
            SELECT 
                Agent_ID,
                Name,
                total_sales_revenue,
                total_sales_count,
                DENSE_RANK() OVER(ORDER BY total_sales_revenue DESC) AS Ranking
            FROM agent_revenue
            )
            SELECT * 
            FROM ranked_agents
            WHERE Ranking <= 5;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Agent_ID         Name total_sales_revenue  total_sales_count  Ranking
0    A0011  Agent A0011            27882272                 24        1
1    A0042  Agent A0042            27191606                 25        2
2    A0043  Agent A0043            24102418                 20        3
3    A0035  Agent A0035            22725752                 21        4
4    A0014  Agent A0014            22034008                 21        5

### 21.Which agents close deals fastest?

In [73]:
query = """
            SELECT Agent_ID, Name, Avg_Closing_Days
            FROM agents
            ORDER BY Avg_Closing_Days LIMIT 5;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Agent_ID         Name  Avg_Closing_Days
0    A0048  Agent A0048                15
1    A0035  Agent A0035                20
2    A0042  Agent A0042                21
3    A0023  Agent A0023                23
4    A0045  Agent A0045                26

### 22.Does experience correlate with deals closed?

In [76]:
query = """
            SELECT
                (
                    COUNT(*) * SUM(Experience_Years * Deals_Closed)
                    - SUM(Experience_Years) * SUM(Deals_Closed)
                ) /
                SQRT(
                    (COUNT(*) * SUM(Experience_Years * Experience_Years)
                    - POW(SUM(Experience_Years), 2)) *
                    (COUNT(*) * SUM(Deals_Closed * Deals_Closed)
                    - POW(SUM(Deals_Closed), 2))
                ) AS correlation_experience_and_deals
            FROM agents;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

   correlation_experience_and_deals
0                          0.125188

### 23.Do agents with higher ratings close deals faster?

In [77]:
query = """
            SELECT 
                CASE
                    WHEN Rating >=1 AND Rating <=2 THEN '1-2'
                    WHEN Rating > 2 AND Rating <=3 THEN '2-3'
                    WHEN Rating > 3 AND Rating <= 4 THEN '3 - 4'
                    WHEN Rating > 3.5 AND Rating <= 4 THEN '3.5 - 4'
                    WHEN Rating > 4 AND Rating <= 4.5 THEN '4 -4.5'
                    WHEN Rating > 4.5 AND Rating <= 5 THEN '4.5 - 5'
                END AS rating_range,
                AVG(Avg_Closing_Days)
            FROM agents
            GROUP BY rating_range
            ORDER BY rating_range DESC;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  rating_range AVG(Avg_Closing_Days)
0      4.5 - 5               50.6667
1       4 -4.5               53.8571
2        3 - 4               58.2963

### 24.What is the average commission earned by each agent?

In [78]:
query = """
            SELECT 
                a.Agent_ID,
                ROUND((s.Sale_Price * a.Commission_Rate) / 100) AS Commission_price
            FROM agents a
            INNER JOIN listing l
                ON a.Agent_ID = l.Agent_ID
            INNER JOIN sales s
                ON l.Listing_ID = s.Listing_ID
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

    Agent_ID Commission_price
0      A0040            18512
1      A0015             1054
2      A0011            36504
3      A0025            38642
4      A0030            23298
..       ...              ...
715    A0008             5642
716    A0012            38358
717    A0036            25893
718    A0046            27962
719    A0014            10079

[720 rows x 2 columns]

### 25.Which agents currently have the most active listings?

In [79]:
query = """
            SELECT 
                a.Agent_ID,
                a.Name,
                COUNT(l.Listing_ID) AS Active_Listings
            FROM agents a
            INNER JOIN listing l
                ON a.Agent_ID = l.Agent_ID
            LEFT JOIN sales s
                ON l.Listing_ID = s.Listing_ID
            WHERE s.Listing_ID IS NULL
            GROUP BY a.Agent_ID
            ORDER BY Active_Listings DESC LIMIT 10;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Agent_ID         Name  Active_Listings
0    A0023  Agent A0023              446
1    A0011  Agent A0011              439
2    A0008  Agent A0008              438
3    A0042  Agent A0042              435
4    A0014  Agent A0014              432
5    A0044  Agent A0044              430
6    A0020  Agent A0020              426
7    A0012  Agent A0012              425
8    A0015  Agent A0015              425
9    A0048  Agent A0048              425

## Buyer & Financing Behavior

### 26. What percentage of buyers are investores vs end users?

In [80]:
query = """
            SELECT 
                Buyer_Type,
                COUNT(*) AS Count,
                ROUND(100 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS Percentage
            FROM buyers
            GROUP BY Buyer_Type;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Buyer_Type  Count Percentage
0   End User  10020      50.10
1   Investor   9980      49.90

### 27. Which cities have the highest loan uptake rate

In [81]:
query = """
            SELECT 
                l.City,
                SUM(b.Loan_Taken) AS Number_of_Loan
            FROM buyers b
            INNER JOIN sales s
                ON b.Sale_ID = s.Listing_ID
            INNER JOIN listing l
                ON s.Listing_ID = l.Listing_ID
            GROUP BY l.City
            ORDER BY Number_of_Loan DESC;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

          City Number_of_Loan
0      Phoenix           2313
1      Chicago           2188
2     New York           1913
3  Los Angeles           1811
4      Houston           1809

### 28. What is the average loan amount by buyer type?

In [82]:
query = """
            SELECT 
                Buyer_Type,
                AVG(Loan_Amount) AS Avg_Loan_Amount
            FROM Buyers
            GROUP BY Buyer_Type;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Buyer_Type Avg_Loan_Amount
0   End User    2599433.8242
1   Investor    2629271.9423

### Which payment mode is most commonly used?

In [83]:
query = """
            SELECT
                Payment_Mode,
                COUNT(Payment_Mode) AS Payment_Method
            FROM buyers
            GROUP BY Payment_Mode
            ORDER BY Payment_Method DESC;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

    Payment_Mode  Payment_Method
0           Cash            5088
1            UPI            5012
2         Cheque            4951
3  Bank Transfer            4949

### 30.Do loan-backed purchases take longer to close?

In [84]:
query = """
            SELECT 
                CASE 
                    WHEN b.Loan_Taken = 1 THEN 'Loan Buyers'
                    ELSE 'Non-Loan Buyers'
                END AS Buyer_Financing_Type,
                COUNT(*) AS Buyers_Count,
                ROUND(AVG(s.Days_on_Market)) AS Avg_days_on_Market
            FROM buyers b
            INNER JOIN sales s
                ON b.sale_Id = s.Listing_ID
            GROUP BY Buyer_Financing_Type
            ORDER BY Buyer_Financing_Type;
        """

mycursor.execute(query)

r = mycursor.fetchall()

c = [i[0] for i in mycursor.description]

pd.DataFrame(r, columns = c)

  Buyer_Financing_Type  Buyers_Count Avg_days_on_Market
0          Loan Buyers         10034                 62
1      Non-Loan Buyers          9966                 61